import Header from "@components/header";
import Footer from "@components/footer";
import '@styles/globals.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="mt-5">{children}</main> {/* Adds top margin */}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
